Get-AppxPackage *3dbuilder* | Remove-AppxPackage 
Get-AppxPackage *WindowsAlarms* | Remove-AppxPackage 
Get-AppxPackage *officehub* | Remove-AppxPackage 
Get-AppxPackage *Facebook* | Remove-AppxPackage 
Get-AppxPackage *WindowsFeedbackHub* | Remove-AppxPackage 
Get-AppxPackage *Getstarted* | Remove-AppxPackage 
Get-AppxPackage *MinecraftUWP* | Remove-AppxPackage 
Get-AppxPackage *getstarted* | Remove-AppxPackage 
Get-AppxPackage *bingweather* | Remove-AppxPackage 
Get-AppxPackage *bingfinance* | Remove-AppxPackage 
Get-AppxPackage *OneNote* | Remove-AppxPackage 
Get-AppxPackage *bingweather* | Remove-AppxPackage 
Get-AppxPackage *MicrosoftSolitaireCollection* | Remove-AppxPackage
Get-AppxPackage *bingfinance* | Remove-AppxPackage 
Get-AppxPackage *OneNote* | Remove-AppxPackage 
Get-AppxPackage *Netflix* | Remove-AppxPackage 
Get-AppxPackage *MSPaint* | Remove-AppxPackage 
Get-AppxPackage *Microsoft3DViewer* | Remove-AppxPackage 
Get-AppxPackage *MicrosoftStickyNotes* | Remove-AppxPackage 
Get-AppxPackage *WindowsStore* | Remove-AppxPackage
Get-AppxPackage *bingsports* | Remove-AppxPackage 
Get-AppxPackage *maps* | Remove-AppxPackage 
Get-AppxPackage *communi* | Remove-AppxPackage 
Get-AppxPackage *windowsphone* | Remove-AppxPackage
